### ISSUE TITLE
deploy sensors from all device types

### ISSUE THREAD

**Issue by simmhan** [dream-lab/VIoLET#10]

**Comment by sbshrey** [comment]
need some clarifications

Right now, half of the devices are randomly selected to be act as publisher and the remaining subscriber. Are you asking to set all devices to be publisher?

The publisher act as 1 sensor and produces observation for 3 minutes at every second.

**Comment by sbshrey** [comment]
The sensors from all device types has sensor links to access the sensor's data like http://10.0.5.16:5000/sensors/Edge-5.14_accelerometer_1 which is accessible within that private network by connected devices.
