### ISSUE TITLE
user's docker image extension

### ISSUE THREAD

**Issue by simmhan** [dream-lab/VIoLET#3]

**Comment by shreyas-badiger** [comment]
Can you please give more details on this? With the current implementation, the user can extend our docker image (our image has Centos as the base image for now) and mention the same in infra_config.json file

**Comment by simmhan** [comment]
Users should be able to specify images on a per-device type basis -- with the requirement that it extend from our base image -- and use it in the infra config. Make sure the feature is well documented and tested. A related issue I've opened is to post our violet image to dream:lab's docker hub.
