### ISSUE TITLE
add sensor sanity check to codebase

### ISSUE THREAD

**Issue by simmhan** [dream-lab/VIoLET#38]

**Comment by sbshrey** [comment]
sensor's sanity check file is added in github. This check also gives the plot for deviation in latency for all the private networks as latency_deviation.png

QoS = 1 (sends message atleast once) is set for both devices in handshake.

![latency_deviation](https://user-images.githubusercontent.com/12729780/41806968-e97b966e-76e4-11e8-9a3d-ad2885713cd0.png)

The deviation is calculated as (observed - expected) / expected * 100 where expected = latency of private network * 4 (device 1 --> pub to Fog --> broker to device --> sub then device2 --> pub to Fog --> broker to device1 --> sub )

**Comment by sbshrey** [comment]
added
